# config.yaml

app:
  host: 0.0.0.0
  localPort: 8080
  publicPort: null
  root: /

websocket:
  localPort: 8081
  publicPort: null

cache:
  maxAge: 0
  dotfiles: ignore
  redirect: true

session:
  name: sid
  secret: 8w7lQHUDxYKejFe29zSMMCd0muhHpRPN
  proxy: null
  resave: true
  saveUninitialized: true
  cookie:
    maxAge: 86400000

auth:
  user: null
  pass: foobar
  deadtime: 5000

agenda:
  db:
    address: localhost:27017/agenda-example
    collection: agendaJobs
  name: homectrl queue
  processEvery: 30 seconds
  maxConcurreny: 20
  defaultConcurrency: 5
  defaultLockLifetime: 120000

client:
  useCdn: false
  logging: true

logging:
  levels:
    all: 0
    access: 10
    debug: 20
    info: 30
    warning: 40
    error: 50
    fatal: 60

  colors:
    all: white
    access: magenta
    debug: cyan
    info: green
    warning: yellow
    error: red
    fatal: red

  transports:
    Console:
      - level: all
        colorize: true

    File:
      - level: all
        colorize: false
        handleExceptions: true
