# logging.yaml

logging:

  levels:
    all: 0
    access: 10
    debug: 20
    info: 30
    warning: 40
    error: 50
    fatal: 60

  colors:
    all: white
    access: magenta
    debug: cyan
    info: green
    warning: yellow
    error: red
    fatal: red

  transports:
    Console:
      - level: all
        colorize: true

    File:
      - level: all
        colorize: false
        handleExceptions: true
